version: "2.4"

services:
  api:
    build:
      context: .
      dockerfile: StoreVisitTrackingSystem.Api/Dockerfile
    ports:
      - "7237:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__StoreVisitContext=Server=mysql;Port=3306;Database=storevisitdb;User=root;Password=fbr19072001-

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: fbr19072001-
      MYSQL_DATABASE: storevisitdb
    volumes:
      - mysql-data:/var/lib/mysql
      - ./Scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pfbr19072001-"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
